# Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
# Desc: Create a namespace called easyshop
# Date: 2021-06-05
# Author: Vikas Surve
kind: namespace
apiVersion: v1

metadata:
  name: easyshop
