apiVersion: v1
kind: Secret

metadata:
  name: easyshop-secrets
  namespace: easyshop
type: Opaque
stringData:
  JWT_SECRET: "903360fc8b0d9abd143a3f5e847a9927d66cfc0c9de882bb1da6220f66212b9d"
  NEXTAUTH_SECRET: "6kOfIWLJMwW/kD7qcYvUXQdAQgGXmN6SqsB34YAnQs4="
