apiVersion: v1
kind: Secret

metadata:
  name: easyshop-secrets
  namespace: easyshop
type: Opaque
stringData:
  JWT_SECRET: "c1c8f480a12b59426e5b0208611488b364752c0035f19d122940c1c337fba99c"
  NEXTAUTH_SECRET: "IC+3WMw6s9/MyCm9/thK211tMAnaQq23MCZDgcElEZE="
