apiVersion: v1
kind: Service
metadata:
  name: easyshop-service
  namespace: easyshop
spec:
  type: NodePort # Or ClusterIP if not exposing externally
  selector:
    app: easyshop
  ports:
  - protocol: TCP
    port: 80 # Exposed service port
    targetPort: 3000 # Change this to match your app's internal port
    nodePort: 30000 # Only needed if using NodePort
