apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration-job
  labels:
    app: easyshop
spec:
  template:
    metadata:
      labels:
        app: easyshop
    spec:
      containers:
      - name: easyshop-migration-job
        image: vmsurve/easy-shop-migration:latest
        imagePullPolicy: Always
        env:
        - name: MONGODB_URI
          value: mongodb://mongodb-service:27017/easyshop
      restartPolicy: OnFailure
